"""added_share_column

Revision ID: 78a95f093588
Revises: 2c3439e0d75d
Create Date: 2024-01-03 16:54:12.886207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78a95f093588'
down_revision: Union[str, None] = '2c3439e0d75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('shared_with', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'shared_with')
    # ### end Alembic commands ###
